files:
  - source: /config/locales/en.yml
    translation: /config/locales/%two_letters_code%.yml
  - source: /config/locales/en.decidim-accountability.yml
    translation: /config/locales/%two_letters_code%.decidim-accountability.yml
  - source: /config/locales/en.decidim-admin.yml
    translation: /config/locales/%two_letters_code%.decidim-admin.yml
  - source: /config/locales/en.decidim-api.yml
    translation: /config/locales/%two_letters_code%.decidim-api.yml
  - source: /config/locales/en.decidim-assemblies.yml
    translation: /config/locales/%two_letters_code%.decidim-assemblies.yml
  - source: /config/locales/en.decidim-blogs.yml
    translation: /config/locales/%two_letters_code%.decidim-blogs.yml
  - source: /config/locales/en.decidim-budgets.yml
    translation: /config/locales/%two_letters_code%.decidim-budgets.yml
  - source: /config/locales/en.decidim-comments.yml
    translation: /config/locales/%two_letters_code%.decidim-comments.yml
  - source: /config/locales/en.decidim-conferences.yml
    translation: /config/locales/%two_letters_code%.decidim-conferences.yml
  - source: /config/locales/en.decidim-consultations.yml
    translation: /config/locales/%two_letters_code%.decidim-consultations.yml
  - source: /config/locales/en.decidim-core.yml
    translation: /config/locales/%two_letters_code%.decidim-core.yml
  - source: /config/locales/en.decidim-debates.yml
    translation: /config/locales/%two_letters_code%.decidim-debates.yml
  - source: /config/locales/en.decidim-dev.yml
    translation: /config/locales/%two_letters_code%.decidim-dev.yml
  - source: /config/locales/en.decidim-elections.yml
    translation: /config/locales/%two_letters_code%.decidim-elections.yml
  - source: /config/locales/en.decidim-forms.yml
    translation: /config/locales/%two_letters_code%.decidim-forms.yml
  - source: /config/locales/en.decidim-generators.yml
    translation: /config/locales/%two_letters_code%.decidim-generators.yml
  - source: /config/locales/en.decidim-initiatives.yml
    translation: /config/locales/%two_letters_code%.decidim-initiatives.yml
  - source: /config/locales/en.decidim-meetings.yml
    translation: /config/locales/%two_letters_code%.decidim-meetings.yml
  - source: /config/locales/en.decidim-pages.yml
    translation: /config/locales/%two_letters_code%.decidim-pages.yml
  - source: /config/locales/en.decidim-participatory_processes.yml
    translation: /config/locales/%two_letters_code%.decidim-participatory_processes.yml
  - source: /config/locales/en.decidim-proposals.yml
    translation: /config/locales/%two_letters_code%.decidim-proposals.yml
  - source: /config/locales/en.decidim-sortitions.yml
    translation: /config/locales/%two_letters_code%.decidim-sortitions.yml
  - source: /config/locales/en.decidim-surveys.yml
    translation: /config/locales/%two_letters_code%.decidim-surveys.yml
  - source: /config/locales/en.decidim-system.yml
    translation: /config/locales/%two_letters_code%.decidim-system.yml
  - source: /config/locales/en.decidim-verifications.yml
    translation: /config/locales/%two_letters_code%.decidim-verifications.yml
