files:
  - source: /config/locales/en.yml
    translation: /config/locales/%locale%.yml
  - source: /config/locales/en.decidim-accountability.yml
    translation: /config/locales/%locale%.decidim-accountability.yml
  - source: /config/locales/en.decidim-admin.yml
    translation: /config/locales/%locale%.decidim-admin.yml
  - source: /config/locales/en.decidim-api.yml
    translation: /config/locales/%locale%.decidim-api.yml
  - source: /config/locales/en.decidim-assemblies.yml
    translation: /config/locales/%locale%.decidim-assemblies.yml
  - source: /config/locales/en.decidim-blogs.yml
    translation: /config/locales/%locale%.decidim-blogs.yml
  - source: /config/locales/en.decidim-budgets.yml
    translation: /config/locales/%locale%.decidim-budgets.yml
  - source: /config/locales/en.decidim-comments.yml
    translation: /config/locales/%locale%.decidim-comments.yml
  - source: /config/locales/en.decidim-conferences.yml
    translation: /config/locales/%locale%.decidim-conferences.yml
  - source: /config/locales/en.decidim-consultations.yml
    translation: /config/locales/%locale%.decidim-consultations.yml
  - source: /config/locales/en.decidim-core.yml
    translation: /config/locales/%locale%.decidim-core.yml
  - source: /config/locales/en.decidim-debates.yml
    translation: /config/locales/%locale%.decidim-debates.yml
  - source: /config/locales/en.decidim-dev.yml
    translation: /config/locales/%locale%.decidim-dev.yml
  - source: /config/locales/en.decidim-elections.yml
    translation: /config/locales/%locale%.decidim-elections.yml
  - source: /config/locales/en.decidim-forms.yml
    translation: /config/locales/%locale%.decidim-forms.yml
  - source: /config/locales/en.decidim-generators.yml
    translation: /config/locales/%locale%.decidim-generators.yml
  - source: /config/locales/en.decidim-initiatives.yml
    translation: /config/locales/%locale%.decidim-initiatives.yml
  - source: /config/locales/en.decidim-meetings.yml
    translation: /config/locales/%locale%.decidim-meetings.yml
  - source: /config/locales/en.decidim-pages.yml
    translation: /config/locales/%locale%.decidim-pages.yml
  - source: /config/locales/en.decidim-participatory_processes.yml
    translation: /config/locales/%locale%.decidim-participatory_processes.yml
  - source: /config/locales/en.decidim-proposals.yml
    translation: /config/locales/%locale%.decidim-proposals.yml
  - source: /config/locales/en.decidim-sortitions.yml
    translation: /config/locales/%locale%.decidim-sortitions.yml
  - source: /config/locales/en.decidim-surveys.yml
    translation: /config/locales/%locale%.decidim-surveys.yml
  - source: /config/locales/en.decidim-system.yml
    translation: /config/locales/%locale%.decidim-system.yml
  - source: /config/locales/en.decidim-verifications.yml
    translation: /config/locales/%locale%.decidim-verifications.yml
